---
# 
# redir role teardown
# 
- name: null:socat - stop service
  service:
    name: socat
    state: stopped
  ignore_errors: true

- name: null:socat - uninstall packages
  apt:
    name: socat
    state: absent
    update_cache: yes

- name: null:socat - remove socat.service files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /lib/systemd/system/socat.service
    - /root/socat-output
  ignore_errors: true

- name: null:apache - stop service
  service:
    name: apache2
    state: stopped
  ignore_errors: true

- name: null:apache - uninstall packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    update_cache: yes
  with_items:
    - apache2
    - apache2-utils
    - apache2.2-bin
    - apache2-common

- name: null:iptables - disable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present

- name: null:iptables - clear input accept
  iptables:
    chain: INPUT
    jump: ACCEPT

- name: null:iptables - clear forward accept
  iptables:
    chain: FORWARD
    jump: ACCEPT

- name: null:iptables - clear output accept
  iptables:
    chain: OUTPUT
    jump: ACCEPT

- name: null:iptables - flush nat table
  iptables:
    table: nat
    flush: true

- name: null:iptables - flush mangle table
  iptables:
    table: mangle
    flush: true

- name: null:iptables - flush all
  iptables:
    flush: true
# 
# <<< redir role teardown
# 