---
- name: redir:apache - install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apache2

- name: redir:apache - enable mod_rewrite
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - proxy
    - proxy_http
  notify:
    - restart apache2

- name: redir:apache - set listen_port
  replace:
    path: /etc/apache2/ports.conf
    regexp: '(?P<pre>000-default.conf\n\nListen\s+)(?P<listen_port>\d+)'
    replace: '\g<pre>{{ listen_port }}'
  notify:
    - restart apache2

- name: redir:apache - copy default site template
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0644

- name: redir:apache - set vhost to listen_port
  replace: 
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '(?P<pre>VirtualHost\s+\*:)(?P<listen_port>\d+)'
    replace: '\g<pre>{{ listen_port }}'
  notify:
    - restart apache2

- name: redir:apache - set vhost to listen_port
  replace: 
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '(?P<pre>VirtualHost\s+\*:)<listen_port>(?P<end>>)'
    replace: '\g<pre>{{ listen_port }}\g<end>'
  notify:
    - restart apache2

- name: redir:apache - copy htaccess file
  template:
    src: apache_htaccess
    dest: /var/www/html/.htaccess
    mode: 0644

- name: redir:apache - replace template vars
  replace:
    path: /var/www/html/.htaccess
    regexp: '^(?P<pre>RewriteRule.+)<forward_host>(?P<mid>:)<forward_port>(?P<post>.+)'
    replace: '\g<pre>{{ forward_host }}\g<mid>{{ forward_port }}\g<post>'
