---
- name: upgrade packages
  apt:
    upgrade: dist

- name: install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - netcat
    - sudo

- name: check redirector profile for iptables
  import_tasks: iptables.yml
  when: profile == "iptables"

- name: check redirector profile for socat
  import_tasks: socat.yml
  when: profile == "socat"

- name: check redirector profile for apache
  import_tasks: apache.yml
  when: profile == "apache"
